module.exports = {
  DEFAULT_REQUEST_TIMEOUT : 10000,
  DEFAULT_PORT : 51828,
  DEFAULT_SENSOR_TIMEOUT : 5000,
  DEFAULT_CACHE_DIR : "./.node-persist/storage",
  DEFAULT_LISTEN_HOST : "0.0.0.0",
  COVERS_REQUEST_TIMEOUT : 35000,
  CONTEXT_FROM_WEBHOOK : "fromHTTPWebhooks",
  CONTEXT_FROM_TIMEOUTCALL : "fromTimeoutCall",
  CERT_VERSION : 2,
  CERT_DAYS : 365
};